name: CD Pipeline

on:
  push:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: [self-hosted, shopdesk]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: .next 
          key: build-${{ github.sha }}
          restore-keys: |
            build-

      - name: Save current commit hash
        id: save_commit
        run: echo "CURRENT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Determine port and environment
        id: determine_port_env
        run: |
          if [ "${{ github.ref_name }}" == "staging" ]; then
            echo "PORT=7777" >> $GITHUB_ENV
            echo "ENV=staging" >> $GITHUB_ENV
          else
            echo "PORT=3000" >> $GITHUB_ENV
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Deploy to Staging or Production
        if: github.ref_name == 'staging' || github.ref_name == 'main'
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_KEY: ${{ secrets.SSH_KEY }}  # Use the PEM key from GitHub secrets
          PORT: ${{ env.PORT }}  # Use the determined port
          ENV: ${{ env.ENV }}  # Use the determined environment
        run: |
          echo "$SSH_KEY" > deploy_key.pem  # Write the PEM key to a file
          chmod 600 deploy_key.pem  # Set the correct permissions for the PEM file
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem "$SSH_USERNAME@$SSH_IP" "
            cd shopdesk-fe &&
            git checkout ${{ github.ref_name }} &&
            git reset --hard HEAD &&
            git pull origin ${{ github.ref_name }} &&
            pm2 delete shopdesk-${{ github.ref_name }} || true &&
            sudo fuser -k $PORT/tcp || echo 'No process found on port $PORT' &&
            pm2 start \"bun run start:$ENV\" --name \"shopdesk-${{ github.ref_name }}\" --watch
          "

      - name: Rollback on failure
        if: failure()
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_KEY: ${{ secrets.SSH_KEY }}  # Use the PEM key from GitHub secrets
          PORT: ${{ env.PORT }}  # Use the determined port
          ENV: ${{ env.ENV }}  # Use the determined environment
        run: |
          echo "$SSH_KEY" > deploy_key.pem  # Write the PEM key to a file
          chmod 600 deploy_key.pem  # Set the correct permissions for the PEM file
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem "$SSH_USERNAME@$SSH_IP" "
            cd shopdesk-fe &&
            git checkout ${{ github.ref_name }} &&
            git reset --hard ${{ env.CURRENT_COMMIT }} &&
            pm2 delete shopdesk-${{ github.ref_name }} || true &&
            sudo fuser -k $PORT/tcp || echo 'No process found on port $PORT' &&
            pm2 start \"bun run start:$ENV\" --name \"shopdesk-${{ github.ref_name }}\" --watch
          "
