name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - staging
      - main
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, shopdesk]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: .next 
          key: build-${{ github.sha }}
          restore-keys: |
            build-

      - name: Save current commit hash
        id: save_commit
        run: echo "CURRENT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Deploy to Staging or Production
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_KEY: ${{ secrets.SSH_KEY }}  # Use the PEM key from GitHub secrets
        run: |
          echo "$SSH_KEY" > deploy_key.pem  # Write the PEM key to a file
          chmod 600 deploy_key.pem  # Set the correct permissions for the PEM file
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem "$SSH_USERNAME@$SSH_IP" "
            cd shopdesk-fe &&
            git checkout ${{ github.ref_name }} &&
            git reset --hard HEAD &&
            git pull origin ${{ github.ref_name }} &&
            pm2 delete shopdesk-${{ github.ref_name }} || true &&
            sudo fuser -k ${{ github.ref_name == 'staging' ? '7777' : '3000' }}/tcp || echo 'No process found on port ${{ github.ref_name == 'staging' ? '7777' : '3000' }}' &&
            pm2 start \"bun run start:${{ github.ref_name == 'staging' ? 'staging' : 'prod' }}\" --name \"shopdesk-${{ github.ref_name }}\" --watch
          "

      - name: Rollback on failure
        if: failure()
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_KEY: ${{ secrets.SSH_KEY }}  # Use the PEM key from GitHub secrets
        run: |
          echo "$SSH_KEY" > deploy_key.pem  # Write the PEM key to a file
          chmod 600 deploy_key.pem  # Set the correct permissions for the PEM file
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem "$SSH_USERNAME@$SSH_IP" "
            cd shopdesk-fe &&
            git checkout ${{ github.ref_name }} &&
            git reset --hard ${{ env.CURRENT_COMMIT }} &&
            pm2 delete shopdesk-${{ github.ref_name }} || true &&
            sudo fuser -k ${{ github.ref_name == 'staging' ? '7777' : '3000' }}/tcp || echo 'No process found on port ${{ github.ref_name == 'staging' ? '7777' : '3000' }}' &&
            pm2 start \"bun run start:${{ github.ref_name == 'staging' ? 'staging' : 'prod' }}\" --name \"shopdesk-${{ github.ref_name }}\" --watch
          "
